### ISSUE TITLE
Use supplied dsd=… argument for non–structure-specific message

### ISSUE THREAD

**Issue by younggotti** [dr-leo/pandaSDMX#231]
First of all, sorry for the newbie question.
I have the following code:
`ecb = sdmx.Request('ECB', backend='memory')`
`key = dict(FREQ="D", CURRENCY=["AUD","CAD","CHF","CNY","EUR","GBP","JPY","KRW","MXN","USD"], CURRENCY_DENOM="EUR", EXR_TYPE="SP00", EXR_SUFFIX="A")`
`df = ecb.data('EXR', key=key).write().reset_index()`

It works fine with pandaSDMX 1.6.0. But on 1.9.0 I get the following warning:
`pandasdmx.reader.sdmxml - INFO: Use supplied dsd=… argument for non–structure-specific message`
and then this error:
`'DataMessage' object has no attribute 'write'`

What am I doing wrong here? Thanks

**Comment by dr-leo** [comment]
The warning is a nuisance. It should not be raised. But you can safely ignore it. The right method was deprecated already in 1.6. Use the identical method to_pandas

**Comment by younggotti** [comment]
Thanks a lot!
