### ISSUE TITLE
Issue accessing ISTAT data

### ISSUE THREAD

**Issue by mattiadisalvo** [dr-leo/pandaSDMX#135]
Hi all!
I am trying to use pandaSDMX to access ISTAT data, but I run into several problems, which are not raised when trying with e.g. ECB, EUROSTAT.

The very first issue is that when using request the needed ID is ISTAT, but the Agency ID to use when requiring data-flow, structure etc, is not ISTAT but IT1, which needs to be concatenated to the dataset ID. The example below try to access the Population dataset, and download data with key: SEX (SESSO in ISTAT), TOTAL (T in ISTAT).

`from pandasdmx import Request`
`istat = Request('ISTAT')`
`# 1. Agency key to add in dataflow Request: otherwise dataset not found`
`IT1 = "IT1/"`
`# 2. Identify dataflow: population`
`flow_dataset = istat.dataflow(IT1+'22_289')`

I also cannot define directly the DSD using the approach shown in section _5.Basic usage_ of the pandaSDMX guide  as ISTAT dataflow IDs are all numerical 

`dsd = flow_dataset.dataflow.22_289.structure())` 

yet, I can define the metadata using the id of the datastructure 

`metadata = istat.datastructure(IT1+'DCIS_POPRES1')`

The main issue I encounter, however, is that I get _AttributeError: 'NoneType' object has no attribute 'enum'_ when I try to request data (both with normal and structured request)

`data_response = istat.data(resource_id = IT1+'22_289', key={'SESSO': ['T']})`
or
`data_response = Request('ISTAT_S').data(resource_id = IT1+'22_289',
                                    key={'SESSO': ['T']}, dsd=metadata)`

Has anyone already encountered such an issue? Any comments or suggestions are welcome!

**Comment by khaeru** [comment]
Hi! We are currently working on completing [version 1.0](https://github.com/dr-leo/pandaSDMX/milestone/1); I apologize that this is taking a little while. Can you clarify that you are using pandaSDMX version 0.9, the last official release?

If so, I would recommend updating to 1.0.0b2, or to the `master` branch, and then trying again using that code. Your issue sounds very similar to the one fixed in #75, and also reported in #120, so I think it may be already fixed. Please look at those (in particular the latter) for further details and suggestions.

Please leave a comment to let us know if you are still unable to access ISTAT after installing the development version of the package.

**Comment by mattiadisalvo** [comment]
Hi khaeru,
Yes, I am using version 0.9. 
I updated to ver 1.0.0b2 and  I can now identify the dataflow using only the dataset ID (e.g. 22_289 for the population dataset) without adding the agency code IT1:

`<pandasdmx.StructureMessage>`
  `<Header>`
`    id: 'IDREF404'`
  `  prepared: '2020-03-19T18:01:52.5554665+01:00'`
  `  receiver: 'Unknown'`
  `  sender: 'Unknown'`
 ` response: <Response [200]>`
 ` CategoryScheme (1): ISTAT_DW`
 ` Codelist (11): CL_BASE_YEAR CL_ETA1 CL_FLAG CL_FREQ CL_ITTER107 CL_OB...`
 ` ConceptScheme (2): CROSS_DOMAIN VARIAB_ALL`
 ` ContentConstraint (1): CONSTR_22_289`
 ` DataflowDefinition (1): 22_289`
 ` DataStructureDefinition (1): DCIS_POPRES1` 

However, I still get an error when trying the data_response. 

When I try with key SEX (SESSO in ISTAT), TOTAL (T in ISTAT):
`data_response = istat.data(resource_id = IT1+'22_289', key={'SESSO': ['T']})`
`raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://sdmx.istat.it/SDMXWS/rest/data/22_289/...T..
`
When I also add AGE(ETA) Y40-44:
`data_response = istat.data(resource_id = IT1+'22_289', key={'SESSO': ['T'], 'ETA': 'Y40-44'})`
`raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://sdmx.istat.it/SDMXWS/rest/data/22_289/.Y40-44....T..
`
Any suggestions?

**Comment by khaeru** [comment]
@mattiadisalvo it's not really our goal here to provide help for particular data sources. But as an example of how to use the package, maybe this will be useful for others:

As you've already done:
```python
>>> istat = sdmx.Request('ISTAT')
>>> msg = istat.dataflow('22_289')
>>> msg
<pandasdmx.StructureMessage>
  <Header>
    id: 'IDREF732'
    prepared: '2020-03-24T12:05:01.9872576+01:00'
    receiver: 'Unknown'
    sender: 'Unknown'
  response: <Response [200]>
  CategoryScheme (1): ISTAT_DW
  Codelist (11): CL_BASE_YEAR CL_ETA1 CL_FLAG CL_FREQ CL_ITTER107 CL_OB...
  ConceptScheme (2): CROSS_DOMAIN VARIAB_ALL
  ContentConstraint (1): CONSTR_22_289
  DataflowDefinition (1): 22_289
  DataStructureDefinition (1): DCIS_POPRES1

>>> dfd = msg.dataflow['22_289']
```

Look at the dimensions. You've chosen 'SESSO' and 'ETA' to give example keys. But for instance, the dimension 'ITTER107' is represented by a code list, 'CL_ITTER107', that has *more than 11,000* possible values:
```python
>>> dims = dfd.dimensions
>>> [dim.local_representation.enumerated for dim in dfd.structure.dimensions]
[<Codelist: 'CL_FREQ', 8 items>,
 <Codelist: 'CL_ETA1', 313 items>,
 <Codelist: 'CL_ITTER107', 11359 items>,
 <Codelist: 'CL_SEXISTAT1', 7 items>,
 <Codelist: 'CL_STATCIV2', 18 items>,
 <Codelist: 'CL_TIPO_DATO15', 358 items>,
 None]
```

Also, you can look at the constraint for the dataflow definition. This tells you which subset of the values along each dimension you can expect to find actual data for:
```python
>>> msg.constraint.CONSTR_22_289.data_content_region
[ lots of output ]
```
One thing I see is that only the codes '1', '2', and '9' are used along the 'SESSO' dimension. That dimension is enumerated by the code list 'CL_SEXISTAT1':
```python
>>> msg.codelist.CL_SEXISTAT1.items
{'T': <Code: 'T'='total'>,
 'M': <Code: 'M'='males'>,
 '2': <Code: '2'='females'>,
 '1': <Code: '1'='males'>,
 '3': <Code: '3'='n.a.'>,
 '9': <Code: '9'='total'>,
 'F': <Code: 'F'='females'>}
```
This means that SESSO='T' is not in this data flow, at all. Your example queries were never going to return any items.

To debug using a smaller query, pick a single value along the *largest* dimension:
```python
>>> data_msg = istat.data('22_289', key={'ITTER107': '087015'})
>>> data_msg
<pandasdmx.DataMessage>
  <Header>
    id: 'IREF144d3b74fadb46829921d5f4cbe0a502'
    prepared: '2020-03-24T12:37:48'
    sender: 'SOME_NSI'
  response: <Response [200]>
  DataSet (1)
  dataflow: <DataflowDefinition: 'IT1_DCIS_POPRES1_1_3'=''>
  observation_dimension: <Dimension: TIME_PERIOD>
>>> sdmx.to_pandas(data_msg)
FREQ  ETA      ITTER107  SESSO  STATO_CIV  TIPO_INDDEM  TIME_PERIOD
A     TOTAL    087015    1      1          JAN          2012           67521.0
                                                        2013           66818.0
                                                        2014           74543.0
                                                        2015           75508.0
                                                        2016           73797.0
                                                                        ...
      Y_GE100  087015    9      99         JAN          2015             101.0
                                                        2016             139.0
                                                        2017             130.0
                                                        2018              74.0
                                                        2019              81.0
Name: value, Length: 12564, dtype: float64
```
This works fine. As you can see, there are about 12,500 rows. If there are a similar number for every point along the 'ITTER107' dimension, an unconstrained query could include roughly 142 million observations. Each service is different, but it wouldn't be unreasonable for it to refuse to send you such an enormous message, and instead give some kind of error like a 404.

Unfortunately, sometimes the services' error messages are not informative or constructive. pandaSDMX can only give you the means to dig into the data structure and try to construct a working query.

Please close the issue if this at least lets you move forward!

**Comment by mattiadisalvo** [comment]
Hi @khaeru,
Thank you very much for this, extremely clear and super helpful!
